### ISSUE TITLE
I guess this is still work in progress?

### ISSUE THREAD

**Issue by MrDibbley** [forknote/monero-generator#2]
i gather you are still working on this?

Thanks

**Comment by luiscosio** [comment]
Do you need any help?

**Comment by davidealva** [comment]
I just came across this trying to use the cryptonote generator, does this function the same utilizing the config json tool (http://forknote.net/create/) on Forknote?

**Comment by wanghaisheng** [comment]
is there any more complete explanation about this repo step by step
https://ethereum.org/token

**Comment by luiscosio** [comment]
@wanghaisheng You need to use forknote for the moment, come join us at https://t.me/forknote

**Comment by pmitchev** [comment]
It is work in process. So far you can make simple clones and AEON is working, but there is no documentation and if you want to explore, you have to do it on your own. You can see AEON's config as guideline and see the cryptonote generator for how some similar documentation
