### ISSUE TITLE
Monero Genesis marker tx

### ISSUE THREAD

**Issue by fengshuicoin** [forknote/monero-generator#7]
Seems maybe monero has an added genesis that monero-generator doesnt account for? Im just learning how to make this work. Extensions/core/monero.json maybe needs to be updated??? Anyone more involved in this project i can talk to, and help get this working?

**Comment by shopglobal** [comment]
Contact request sent feel free to reach out

**Comment by shopglobal** [comment]
Telegram: Interchained
Discord: Interchained

**Comment by fengshuicoin** [comment]
You have working monero-generator?

**Comment by fengshuicoin** [comment]
Discord link??

**Comment by shopglobal** [comment]
Yes 

Search discord: interchained

**Comment by fengshuicoin** [comment]
Send invite link i cant find how to search server

**Comment by shopglobal** [comment]
Get on telegram and tell me your username, or tell me your discord name and I will find you. I don't have a group.

**Comment by fengshuicoin** [comment]
https://discord.gg/nwVSRZ

**Comment by pmitchev** [comment]
Fixed: https://github.com/forknote/monero-generator/commit/ae7d4e2b065acdd8524c5bbf7613003425bf7b41

Pull request are more than welcomed, if some of you guys have fixes for other issues.

**Comment by fengshuicoin** [comment]
@pmitchev have discord? Has there been any successful cross overs with this yet?

**Comment by fengshuicoin** [comment]
Ive tried with defaults in configs and non has worked wownero seems to be closest

**Comment by fengshuicoin** [comment]
Guys be careful interchained not sure about this guy but he feels sketchy af. Full of false promises. Luckily for me i trust my own skills more than words of stranger. I might have quick fix monero-generator of my own. Just testing now.

**Comment by shopglobal** [comment]
I'm not helping you because you're aggressive and pushy 

Good luck

**Comment by fengshuicoin** [comment]
Your entitled to your opinion but i feel like your some type of trickster.
Im not aggressive im defensive about my project. And i am a person who gets
things done right away. I dont play around.
Theres no point in you doing my project for me when i can do it my self.
Only i asked if you want to share your method. You never offered any proof
of what you said you can do. Then you delete and remove all contact. So
theres something very scamy about you. I dont trust you

Im open to help and share with others who are interested in this. For now i
will finish my test and confirm its working 100% first.

**Comment by pmitchev** [comment]
Please make pull requests if possible. For genesis tx hex you can use forknoted or http://forknote.net/create/#/ for now. Be aware the _Emission speed factor_ is not the same thing in Monero, and _Difficulty target_ must be 60*N

**Comment by fengshuicoin** [comment]
@pmitchev yea caught that error when building from src. If you build from src you will also have issue with blob block in cryptonote_format_utils.cpp. I also dont get the seed node or dns look up i guess can just change in net_node.h seed.monero.se to server ip 127.0.0.1:8081.

Have you had successful cross over from cryptonote to monero code yet @pmitchev?
